# Generated by Django 5.2.7 on 2025-11-02 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('RESTOCK', '재입고 알림'), ('PRICE_DROP', '가격 변동 알림'), ('PROMOTION', '프로모션 알림')], max_length=20)),
                ('channel', models.CharField(choices=[('IN_APP', '앱 알림'), ('EMAIL', '이메일'), ('SMS', '문자')], default='IN_APP', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('SCHEDULED', '예약됨'), ('SENT', '발송 완료'), ('CANCELED', '취소'), ('FAILED', '실패')], default='PENDING', max_length=12)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('extra_payload', models.JSONField(blank=True, default=dict)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='product.product')),
                ('product_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='product.productoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='notificatio_user_id_7088ed_idx'), models.Index(fields=['notification_type', 'status'], name='notificatio_notific_a659f1_idx'), models.Index(fields=['scheduled_for'], name='notificatio_schedul_cf7340_idx')],
            },
        ),
    ]
