# Generated by Django 5.2.7 on 2025-11-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('OWNER', '사장'), ('MANAGER', '관리자'), ('MEMBER', '회원')], default='MEMBER', help_text='사장/관리자/회원 구분', max_length=20),
        ),
    ]
