# Generated by Django 5.2.7 on 2025-11-02 12:25

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', accounts.models.AccountManager()),
            ],
        ),
    ]
